version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ac_db
      - POSTGRES_USER=ac_user
      - POSTGRES_PASSWORD=ac_pass

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12054801
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: .
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-w@p+fa&&omp^oa7&n68==+0@4^+lert43yw8v8yjhrxip821po
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - POSTGRES_PASSWORD=ac_pass
    depends_on:
      - db

volumes:
  postgres_data:
