# Generated by Django 5.2 on 2025-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شد'), ('done', 'انجام شد')], default='pending', max_length=10, verbose_name='وضعیت')),
            ],
        ),
    ]
