# Generated by Django 5.2 on 2025-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='full_name',
            field=models.CharField(default='بی نام', max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
