# Generated by Django 5.2 on 2025-04-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_servicerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('done', 'انجام شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(max_length=50, verbose_name='نوع سرویس'),
        ),
    ]
