# Generated by Django 5.2 on 2025-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_servicerequest_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(default='unknown', max_length=100, verbose_name='نام مشتری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('install', 'نصب'), ('repair', 'تعمیر')], max_length=10, verbose_name='نوع سرویس'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('done', 'انجام شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
    ]
