# Generated by Django 5.2 on 2025-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_servicerequest_full_name_servicerequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='service_type',
            field=models.CharField(default='نصب', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('done', 'انجام شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
    ]
